### ISSUE TITLE
Fontawesome 5 brands incompatible with Ionic 3 ion-fab

### ISSUE THREAD

**Issue by peterpeterparker** [FortAwesome/Font-Awesome#12437]
Hi,

Using Fontawesome 5 brands in an Ionic 3 project where, for example, button of type `ion-fab` are used too, will produce incompatibility.

When rendering pages, fontawesome will identify `ion-fab` elements has elements to transform in svg which is obviously not correct.

Code example:

    <button ion-fab icon-only>
       <ion-icon name="close"></ion-icon>
    </button>

Will be rendered as:

    <svg icon-only="" ion-fab="" class="svg-inline--fa  fa-w-16 fab-md" ... </svg>
    

How to reproduce:

    git clone https://github.com/peterpeterparker/ionic-fontawesome5
    cd ionic-fontawesome5
    npm install
    ionic serve

<img width="1001" alt="capture d ecran 2018-02-25 a 11 37 06" src="https://user-images.githubusercontent.com/16886711/36640505-5d780f92-1a20-11e8-8e98-b71ace691462.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It happens because of the `fab` class used by this library, which tricks Font Awesome.

@robmadole is there any way to customize FA classes on the SVG framework?

**Comment by robmadole** [comment]
I'm not sure if that is what's going on here. We'll take a look at this one.

**Comment by plchampigny** [comment]
We had the same problem last week when we integrated font-awesome 5 pro. We just didn't integrate the brand part of it. Would really like that to be fixed.

**Comment by peterpeterparker** [comment]
Any news here?

**Comment by robmadole** [comment]
Nope not yet. This hasn't popped the queue yet.

**Comment by peterpeterparker** [comment]
Hope it will soon 😉

**Comment by tagliala** [comment]
@peterpeterparker Sorry but if there is no way of changing the default class of `ion-fab` or Font Awesome's `fab` I cannot help.

Maybe providing a configuration option to ignore a set of attributes when searching for icons in the DOM could help, but this should be done on FA side

Something like:
```js
FontAwesomeConfig = { ignoreAttributes: ['ion-fab', 'data-fa-ignore'] };
```

**Comment by peterpeterparker** [comment]
@tagliala thx for your feedback and idea

let's wait on @robmadole feedback when he will have the time to have a look too

there are millions of Ionic app and developers, so cleaner the solution will be, the better it is

**Comment by mvecchione** [comment]
Same issue here.

**Comment by peterpeterparker** [comment]
Reported soonish 4 months ago, any plan to fix that problem? 

I would love to have the benefit of my font awesome pro license in my product instead of having to stick to v4.7, hope you could figure something out soon

**Comment by cmartin81** [comment]
Any updates on this issue?

**Comment by robmadole** [comment]
Alright @peterpeterparker, I took a closer look at `https://github.com/peterpeterparker/ionic-fontawesome5` and one issue is you are using [some older packages](url) that automatically tried to replace icons. The newer package `@fortawesome/fontawesome-svg-core` and `@fortawesome/free-brands-svg-icons` do not have this issue.

An updated version of `app.component.ts` would be:

```typescript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { fontawesome } from '@fortawesome/fontawesome-svg-core';
import { faFacebookF } from '@fortawesome/free-brands-svg-core';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = 'TabsPage';

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();

      library.add(faFacebookF);
    });
  }
}
```

So that should fix the issue where we are trying to replace non-FA icons. But, it will also cause any real FA icons not to render as well.

I was going to recommend using https://github.com/FortAwesome/angular-fontawesome but I just tried to setup an Ionic 3 and a 4 project and it's not working. So I think we may have some work to do there. However, this is going to be my recommendation when we get it working.

**Comment by peterpeterparker** [comment]
@robmadole thx for the feedback but to be honest this issue is one year old, so to speak frankly, I don't care anymore. Of course I have implemented a long time ago a work around (I ship the brand svg I need in my app as assets). I even migrated to Ionic v4 so no idea if this happens with v4 too.

I just didn't close this issue so far because I thought that the others who subscribed to this issue might still face the issue but I honestly don't mind if we close it.

**Comment by cmartin81** [comment]
I just made my own fab button (with css) it was not hard at all.

**Comment by peterpeterparker** [comment]
Never said it's hard...anyhow then if everybody found a solution then I just close this old issue

P.S.: if you wish me to reopen it, ping me

**Comment by codebymikey** [comment]
This is still an issue, do you mind re-opening, I think having the ability to opt out through a specific class or attribute as suggested in https://github.com/FortAwesome/Font-Awesome/issues/12437#issuecomment-372799981 makes the most sense.

Ran into an issue where I have a DOM element along the lines `<label class="fas fa-caret-up"><input/></label>`, but the client can configure whether to use the CSS or JS based fontawesome methods. The functionality works fine on `CSS` option, but breaks behaviour when certain clients are using the JS-based method, as the JS method loses the `label` as well as the `input`.

Or alternatively provide a way to override the [default JS configurations](https://docs.fontawesome.com/v6/apis/javascript/configuration#accessing-the-configuration) for individual elements.
