### ISSUE TITLE
An unexpected error occurred: "https://npm.fontawesome.com/xxxx-xxxx-xxxx-xxxx/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.1.2.tgz: connect ECONNREFUSED 54.159.213.218:443".

### ISSUE THREAD

**Issue by emmkong** [FortAwesome/Font-Awesome#12609]
We encounter an error when installing `fontawesome-common-types` with yarn

An unexpected error occurred: "https://npm.fontawesome.com/xxxx-xxxx-xxxx-xxxx/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.1.2.tgz: connect ECONNREFUSED 54.159.213.218:443".

**Comment by positiveflat** [comment]
We had same problem.
> npm ERR! FetchError: request to https://npm.fontawesome.com/8A478AAC-0AD0-4929-B416-AE745BDD0FC3/@fortawesome/fontawesome-free-regular/-/fontawesome-free-regular-5.0.6.tgz failed, reason: connect ECONNREFUSED 54.159.213.218:443

**Comment by sunnyrjuneja** [comment]
Same but with pro light.

**Comment by Radau** [comment]
Seems like the registry is currently down? Nothing is installing via that registry for me, had to fall back to using yarnpkg for now to get CI to build. https://registry.yarnpkg.com/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.1.3.tgz

Would be nice if they had a status page for it.

**Comment by Radau** [comment]
@positiveflat You just posted your fontawesome API key, you may want to edit your comment to remove the XXXXXX-XXXX-XXXXX-XXXXX-XXXXXX that comes right after https://npm.fontawesome.com/

**Comment by hoangvn2404** [comment]
@Radau hey how did you  `fall back to using yarnpkg for now to get CI to build`,
I need it too but don't know how to do it? thanks

**Comment by Radau** [comment]
@hoangvn2404 I searched for https://npm.fontawesome.com in my yarn.lock file (will work for package-lock.json as well, just needs a lockfile). Then just replace everything before /@fortawesome with https://registry.yarnpkg.com/

This will not work for Pro level packages that require your API key unfortunately.

**Comment by hoangvn2404** [comment]
@Radau thank you so much, unfortunately I'm on pro package, guess I have to wait for the server go back online

**Comment by chapati23** [comment]
same issue, all our builds are failing and we're unable to deploy currently because of this, we are most likely gonna drop all fontawesome npm packages and use raw SVGs to reduce this dependency

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this and we apologize for the inconvenience.

I've reported this issue everywhere I could but I can't fix this.

> Would be nice if they had a status page for it.

Yes, definitely. The npm registry should be added to https://status.fortawesome.com/ I've also reported this in a private tracker

**Comment by benperiton** [comment]
@chapati23 I'm switching to use a offline-mirror that I can check in once it is back up. At least that way we can still have the benefits of npm packages, abut still operate if it goes down.

https://yarnpkg.com/blog/2016/11/24/offline-mirror/

**Comment by robmadole** [comment]
We are investigating now.

**Comment by robmadole** [comment]
EC2 machine died and our monitoring missed it.

**Comment by robmadole** [comment]
Re-configuring a new instance now.

**Comment by robmadole** [comment]
DNS updated, TTL is 60

**Comment by robmadole** [comment]
npm.fontawesome.com is back online. Sorry about that folks.

**Comment by tagliala** [comment]
@robmadole since @emmkong accidentally disclosed his API key, should he contact us and ask for a key change?

I didn't read that, I'm referring to this comment: https://github.com/FortAwesome/Font-Awesome/issues/12609#issuecomment-373271109

**Comment by robmadole** [comment]
@positiveflat we need to revoke that. Can you get a hold of me through hello@fontawesome.com? I won't shut that one down until you are prepared to update to a new one.

**Comment by positiveflat** [comment]
@robmadole Thanks. I sent message to hello@fontawesome.com.

**Comment by tagliala** [comment]
@elysiopires you should use `registry.npmjs.org` for Font Awesome Free, or check your Auth token if you want to use the Pro registry also for Font Awesome Free 

Check your local or global `.npmrc` for wrong configuration settings

I'm not able to reproduce

Docs: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by Kalifax** [comment]
Happens randomly during builds. Most times it works, but some (random) times it doesn't. 

This is for PRO 5.8.1: 
`error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-solid-svg-icons/-/pro-solid-svg-icons-5.8.1.tgz: ESOCKETTIMEDOUT".`

**Comment by zerdos** [comment]
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.11.2.tgz: unexpected end of file".

**Comment by robmadole** [comment]
We're working on replacing the guts of `npm.fontawesome.com` with a new service. It should be launched within the next couple of weeks. We'll send out announcements but this should vastly improve the reliability of the service.

**Comment by mduleone** [comment]
Hi team! Thanks for all the hard work on this issue! I noticed that on your registry's [status page](https://status.fortawesome.com/), 4 hours ago y'all noted that you're moving  10% of the traffic to the new infrastructure. We're seeing intermittent issues with FontAwesome installs, and it seems to be failing at a 10% rate. I also noticed that there is no update on the status page indicating that systems are down or that an issue is being worked on, or what resolution steps y'all are taking (despite a banner saying some systems are down).

When we can expect an update?

**Comment by robmadole** [comment]
Hi @mduleone . We don't know of any issues with the rollout currently. Please send us a note to hello@fontawesome.com and we'll work through it with you.

**Comment by mduleone** [comment]
@robmadole is there a faster way we can communicate? Email is typically painfully slow, and this is now blocking production deploys for us.

**Comment by robmadole** [comment]
@mduleone I'm waiting for your email right now. But since this could contain security tokens we won't do this in a public GitHub repo.

**Comment by mduleone** [comment]
@robmadole Thanks! Email sent.

**Comment by robjac** [comment]
I'm having this same issue currently. Is the _only_ solution to email @robmadole ?

**Comment by robmadole** [comment]
That's our support channel @robjac. That's the only way :) We have a dedicated support team and if we need you to share your auth token it's a lot better to do it there than publicly share it over GitHub or have you recite it to us a character at a time over the phone.

**Comment by robjac** [comment]
@robmadole thanks for the quick help via email!

**Comment by robmadole** [comment]
@robjac our pleasure! Glad we got it fixed up.

**Comment by MikeFranco** [comment]
Hi! @robmadole I have the same issue, I cant deploy to production since Monday, I send an email, but have received no reply. Could you help me asap?

**Comment by robmadole** [comment]
@MikeFranco I see it! Working on it now.

**Comment by MikeFranco** [comment]
@robmadole Thank you so much for your help! :100:

**Comment by MrFrontend** [comment]
@robmadole I actually still having this same issue 😓
Do you have a troubleshooting guide for it ?

**Comment by robmadole** [comment]
@MrFrontend since this involves security tokens we ask that you send us an email to hello@fontawesome.com

**Comment by robjac** [comment]
> @MrFrontend since this involves security tokens we ask that you send us an email to [hello@fontawesome.com](mailto:hello@fontawesome.com)

@MrFrontend email hello@fontawesome.com and they'll get you fixed up!

**Comment by moltar** [comment]
```
remote:        npm ERR! 404 Not Found - GET https://npm.fontawesome.com/$TOKEN/@fortawesome/vue-fontawesome/-/vue-fontawesome-0.1.5.tgz
```

I have verified that the `$TOKEN` is correct via my [Font Awesome account](https://fontawesome.com/account) page.

**Comment by robmadole** [comment]
@moltar you are using an older authentication method which is no longer supported. Please review the [documentation on creating an `.npmrc` file](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro).

Make sure that you remove any `yarn.lock` or `package-lock.json` file prior to installing again as these files will have the old unsupported URLs in them.

**Comment by moltar** [comment]
Right, I have figured that out after.

But it sucks that:

1. Existing builds are breaking
2. No reasonable explanation
3. No easily Googleable solutions
4. I have not received any notifications about this happening

I think at a minimum the error URL should have steps to mitigate this, instead of just showing a generic 404 page.

**Comment by robmadole** [comment]
@moltar sorry for the frustration! We try hard not to inconvenience our customers but sometimes these types of things are unavoidable. Support for Pro customers is always available at hello@fontawesome.com.

**Comment by aforty** [comment]
This is happening with the free build now. Why? We can't deploy.

An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.12.0/fontawesome-free-5.12.0.tgz: Request failed \"401 Unauthorized\""

**Comment by zerdos** [comment]
oh noo! Until now it happened just with the paying customers! :(

**Comment by robhadfield** [comment]
> @moltar you are using an older authentication method which is no longer supported. Please review the [documentation on creating an `.npmrc` file](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro).
> 
> Make sure that you remove any `yarn.lock` or `package-lock.json` file prior to installing again as these files will have the old unsupported URLs in them.

This would be handy in the documentation right next to the note that tells you to change auth methods 👍🏼

**Comment by tagliala** [comment]
@robhadfield thanks for the suggestion.  We already have a warning on the bottom of that paragraph, so it may be worth to also add this note

@robmadole @talbs what about adding

> Make sure that you remove any yarn.lock or package-lock.json file prior to installing again as these files will have the old unsupported URLs in them.

to 

![image](https://user-images.githubusercontent.com/556268/71726608-e9dee780-2e37-11ea-87ac-f383e22bf9d8.png)

?

**Comment by ralphwilliams** [comment]
> @robhadfield thanks for the suggestion. We already have a warning on the bottom of that paragraph, so it may be worth to also add this note
> 
> @robmadole @talbs what about adding
> 
> > Make sure that you remove any yarn.lock or package-lock.json file prior to installing again as these files will have the old unsupported URLs in them.
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/556268/71726608-e9dee780-2e37-11ea-87ac-f383e22bf9d8.png)
> 
> ?

This was the fix for me. I missed removing my yarn.lock, so that would have been nice when I was reading that note.

**Comment by robhadfield** [comment]
@tagliala - That would help greatly I think 👍

**Comment by robmadole** [comment]
I've updated the docs for this one!

**Comment by InumanSoul** [comment]
Trying to install this to my react project following the webpage instruction and gives me this error (on yarn log files):
`  Error: https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: authentication required
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:66987:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:140748:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:141720:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:141642:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1201:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)`

I added the .yarnrc file with this: 
`"@fortawesome:registry" "https://npm.fontawesome.com/authToken=XXXXX-XXXXX-XXXXX-XXXXX"`

And tried this too: 
`"@fortawesome:registry" "https://npm.fontawesome.com/XXXXX-XXXXX-XXXXX-XXXXX"`

No ones works 😞 ...  What can i do?

**Comment by tagliala** [comment]
Hi, this looks like the old authentication method

Please use `.npmrc` (not `.yarnrc`) as explained here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by Coreusa** [comment]
Still a problem in automated azure builds. Suddenly occurs for pro builds (auth is via .npmrc).

An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-solid-svg-icons/-/5.15.0/pro-solid-svg-icons-5.15.0.tgz: ESOCKETTIMEDOUT"

**Comment by robmadole** [comment]
@Coreusa we have had another report of this as well. Can you provide some information for me?

- Is this part of a CI/CD build?
- If CI/CD, is it on premise or through a cloud service?
- If cloud service, which one?
- Can you provide a trace route from the failing instance to `npm.fontawesome.com`?

**Comment by robmadole** [comment]
@Coreusa also, can you tell us if you are using `yarn` or `npm`?

**Comment by robmadole** [comment]
@Coreusa what Azure region?

**Comment by bkahl** [comment]
Hey guys, seems like the proxy site is down and causing our build to fail. Any ideas
<img width="1137" alt="Screen Shot 2022-07-27 at 5 52 48 PM" src="https://user-images.githubusercontent.com/682453/181382168-3ba30a45-47ce-41f1-a18d-6d6e95a65d73.png">
?

**Comment by robmadole** [comment]
Hi @bkahl. These are normally very short-lived errors with Cloudsmith. If you are still experiencing problems we'd prefer you send us an email to hello@fontawesome.com and we'll get it worked out.
