### ISSUE TITLE
Support public Unicode codepoints where possible

### ISSUE THREAD

**Issue by eevee** [FortAwesome/Font-Awesome#222]
It would be fantastic if I could use codepoints for which appropriate icons already exist, e.g., "★" for the solid star.

A hypothetical screenreader could even then announce the name of the glyph.

**Comment by StanleyMlha** [comment]
+1 : map to Unicode possible code-points

**Comment by karlhorky** [comment]
What's the status of this? Is this still planned for version 5? I took a look and didn't find a pull request for this yet - I'm assuming there isn't one yet due to difficulty of a clean solution.

Is [this](https://github.com/FortAwesome/Font-Awesome/milestones/5.0.0) is the only tracking page for version 5?

**Comment by joewreschnig** [comment]
There is absolutely a clean solution: Put the characters at both the public and private codepoints.

There is no pull request because the fonts are checked in as binary files and it is impossible to submit patches for them.

**Comment by dwt** [comment]
I was directed here to re-report my problem, so here goes:

My main point is that we have found that windows has a 'feature' that allows admins to disable all webfont downloads for all their users. This leads to apps that use font awesome to suddenly loose all icons from the application (in all versions of IE!), usually rendering the app completely unusable. See https://github.com/FortAwesome/Font-Awesome/issues/10046 for the original bug report.

I also think that together with support for content-editable and screen readers reading out the correct characters, it makes _a lot of sense_ to switch to semantic code points, and I'd like to add my voice here.

**Comment by Crissov** [comment]
Will this finally be fixed in Font Awesome 5 – could it be added as a goal to [Kickstarter](https://www.kickstarter.com/projects/232193852/font-awesome-5/)?

**Comment by Crissov** [comment]
Has it been fixed in v5.0.0, the milestone this issue is tagged with? I only see PUA codes in the documentation.

**Comment by tagliala** [comment]
This should be finally available in FA 6 beta

**Comment by sensibleworld** [comment]
Yup! We've been working hard to map our existing icons to standard unicode points. In `6.0.0-beta2` they have been assigned as aliases. We still need to reveal these code points to the end-user, but they exist. (And we still have a ways to go for full parity.)

**Comment by anarchodin** [comment]
@sensibleworld Is that mapping visible to the public anywhere? I'm guessing you could get help finding assignments that are missing.

If that's not an option, I'd at the very least like to ask if you've also checked the 'brands' set of icons. Specifically, a number of the Creative Commons symbols were added to Unicode 13, and the original proposal to add them mentioned Font Awesome including CC symbols as an example of their use.

**Comment by tagliala** [comment]
Available in FA6

**Comment by dwt** [comment]
@tagliala could you provide a pointer where their use is documented?

**Comment by tagliala** [comment]
Let's ask @talbs or @robmadole if this has been documented, I cannot. find references

By using standard unicode point, it is possible to use Font Awesome CSS in this way:

```html
<span class="fas">⭐️</span>
```

Demo: https://jsfiddle.net/tagliala/4f8gp2wL/5/

The same does not apply to SVG/JS

**Comment by robmadole** [comment]
We don't have this documented yet but as @tagliala mentioned it has been implemented for web fonts + CSS.

**Comment by dwt** [comment]
@robmadole do you guys plan to do that, or is the goal to first build support for more codepoints before you make this public?

**Comment by robmadole** [comment]
@dwt yes we have plans to but I don't have an ETA on when that might be. We got a good number of unicode emoji parity with the release of 6.0.0 but there is so much more to do. The unicode spec doesn't align 1:1 with Font Awesome so that can be a challenge.

**Comment by Crissov** [comment]
Of course it doesn't, but if anyone was considering to propose the encoding of additional symbols and pictographs to Unicode, using Font Awesome as an example of existing usage, then proper documentation of existing coverage would certainly help a lot. 

In my not so humble opinion, the non-PUA codepoint should also be made available in the usual character picker interface.

**Comment by sensibleworld** [comment]
@Crissov Of course! As Rob said, it's on our list of improvements to make. And adding the standard Unicode to our UI, in addition to our PUA Unicode, is part of that.
